# Site settings
title: Personal Website
description: A personal website of Chaitanya Kovuri
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://ceekyay.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chaitanya Kovuri
user_description: I'm a Computer Science graduate from The University of Iowa. I currently work as a Software Engineer for Panasonic; building microservices using Java and Spring Framework. Below is what I'm great at.
user_title: Software Engineer
email: ckovuri16@gmail.com
twitter_username: ceekyay
github_username: ceekyay
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
